import type { Metadata } from 'next'
import Header from '@/components/layouts/header'
import localFont from 'next/font/local'
import Providers from '@/providers'
import '@rainbow-me/rainbowkit/styles.css'
import './globals.css'

const myFont = localFont({
  src: [
    {
      path: './fonts/IBMPlexMono-Bold.ttf',
      weight: '700'
    },
    {
      path: './fonts/IBMPlexMono-ExtraLight.ttf',
      weight: '200'
    },
    {
      path: './fonts/IBMPlexMono-Light.ttf',
      weight: '300'
    },
    {
      path: './fonts/IBMPlexMono-Medium.ttf',
      weight: '500'
    },
    {
      path: './fonts/IBMPlexMono-Regular.ttf',
      weight: '400'
    },
    {
      path: './fonts/IBMPlexMono-SemiBold.ttf',
      weight: '600'
    },
    {
      path: './fonts/IBMPlexMono-Thin.ttf',
      weight: '100'
    }
  ],
  display: 'swap',
  variable: '--font-ibm-plex-mono'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${myFont.className} ${myFont.variable} antialiased`}>
        <Providers>
          <Header />
          <main className='flex flex-col gap-2 px-2 py-14 xl:px-20'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
